### ISSUE TITLE
SecurityException While uploading portrait from camera

### ISSUE THREAD

**Issue by therajanmaurya** [therajanmaurya/android-client-2.0#115]
```
FATAL EXCEPTION: main
Process: com.mifos.apache.fineract, PID: 12913
java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE cmp=android/com.android.internal.app.ResolverActivity } from ProcessRecord{4b0a276 12913:com.mifos.apache.fineract/u0a479} (pid=12913, uid=10479) with revoked permission android.permission.CAMERA
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2679)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1574)
at android.app.Activity.startActivityForResult(Activity.java:3934)
at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:959)
at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:948)
at com.mifos.apache.fineract.ui.online.customer.customerprofile.editcustomerprofilebottomsheet.EditCustomerProfileBottomSheet.openCamera(EditCustomerProfileBottomSheet.java:164)
at com.mifos.apache.fineract.ui.online.customer.customerprofile.editcustomerprofilebottomsheet.EditCustomerProfileBottomSheet.checkWriteExternalStoragePermission(EditCustomerProfileBottomSheet.java:144)
at com.mifos.apache.fineract.ui.online.customer.customerprofile.editcustomerprofilebottomsheet.EditCustomerProfileBottomSheet.chooseSelectDeletePhoto(EditCustomerProfileBottomSheet.java:284)
at com.mifos.apache.fineract.ui.online.customer.customerprofile.editcustomerprofilebottomsheet.EditCustomerProfileBottomSheet_ViewBinding$1.doClick(EditCustomerProfileBottomSheet_ViewBinding.java:41)
at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
at android.view.View.performClick(View.java:5207)
at android.view.View$PerformClick.run(View.java:21168)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by therajanmaurya** [comment]
That's why app is crashing https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE
